library(desc)
unlink("DESCRIPTION")
my_desc <- description$new("!new")
my_desc$set("Package", "frankenstein")
my_desc$set("Authors@R", "person('Colin', 'Fay', email = 'contact@colinfay.me', role = c('cre', 'aut'))")
my_desc$del("Maintainer")
my_desc$set_version("0.0.0.9000")
my_desc$set(Title = "Bring your Shiny App back from the dead")
my_desc$set(Description = "Bring your Shiny App back from the dead.")
my_desc$set("URL", "https://github.com/Thinkr-open/frankenstein")
my_desc$set("BugReports", "https://github.com/Thinkr-open/frankenstein/issues")
my_desc$write(file = "DESCRIPTION")

colin::init_docs()
usethis::use_code_of_conduct()
usethis::use_package("attempt")
usethis::use_package("shiny")
usethis::use_package("glue")
usethis::use_package("crayon")
usethis::use_package("yesno")
usethis::use_package("R6")
usethis::use_build_ignore("readme_fig/")
usethis::use_build_ignore("shiny_bookmarks/")
dir.create("readme_fig")
usethis::use_build_ignore("readme_fig/")
usethis::use_lifecycle_badge("Experimental")
usethis::use_tidy_description()

library(attempt)
library(shiny)
library(glue)
library(crayon)
library(yesno)
